Weather Page Finish Main Task
Tparuna1/TBCAcademyTeamWork pull request #4
Opened 2023-12-01 11:55 UTC by MariamKipiani

2023-12-01 11:56 UTC, levanl reviewed
well done !!!

2023-12-01 12:29 UTC, Tparuna1 requested changes
ჩაასწორე კომენტარები და ისე დავმერჯოთ

2023-12-01 12:29 UTC, Tparuna1 commented on EcoTrackerApp/EcoTrackerApp/WeatherPage/WeatherPageVC.swift
>  class WeatherPageVC: UIViewController {
Final უნდა იყოს ეს კლასი

2023-12-01 12:29 UTC, Tparuna1 commented on EcoTrackerApp/EcoTrackerApp/WeatherPage/WeatherPageVC.swift
> +
UISetup func ს უნდა იყოს Private, ამათ ამ კლასის გარეთ ხომ არ იყენებ. (NANA Voice)

2023-12-01 12:29 UTC, Tparuna1 commented on EcoTrackerApp/EcoTrackerApp/WeatherPage/WeatherPageVC.swift
ასევე ესენიც Private

2023-12-01 12:29 UTC, Tparuna1 commented on EcoTrackerApp/EcoTrackerApp/WeatherPage/WeatherPageViewModel.swift
> +class WeatherPageViewModel {
Final

2023-12-01 12:33 UTC, levanl commented on EcoTrackerApp/EcoTrackerApp/WeatherPage/WeatherPageModel.swift
>  //  Created by tornike <parunashvili on 29.11.23.
აქ ზედმეტი კომენტარებია მოსაშორებელი

2023-12-01 13:04 UTC, levanl approved these changes

2023-12-01 13:05 UTC, Tparuna1 approved these changes

2023-12-01 13:05 UTC, slapiashvili approved these changes
approved, great

2023-12-01 14:08 UTC, ketto26 approved these changes
Approved!

2023-12-01 14:23 UTC, ketto26 commented on EcoTrackerApp/EcoTrackerApp/WeatherPage/WeatherPageVC.swift
> +    var viewModel = WeatherPageViewModel()
private

2023-12-01 16:13 UTC, ketto26 requested changes

2023-12-01 16:13 UTC, ketto26 commented on EcoTrackerApp/EcoTrackerApp/WeatherPage/WeatherPageVC.swift
> +    var viewModel = WeatherPageViewModel()
არა, არა:
var viewModel = WeatherPageViewModel() ეს უნდა იყოს private let. 
ზედა class WeatherPageVC: UIViewController ამას არ სჭირდება private

2023-12-01 17:15 UTC, ketto26 approved these changes

2023-12-01 18:27 UTC, merged

2023-12-03 23:21 UTC, NanaJimsheleishvili commented on EcoTrackerApp/EcoTrackerApp/WeatherPage/WeatherPageModel.swift
> +struct WeatherPageModel: Codable {
Decodable

2023-12-03 23:21 UTC, NanaJimsheleishvili commented on EcoTrackerApp/EcoTrackerApp/WeatherPage/WeatherPageModel.swift
> +struct List: Codable {
Decodable

2023-12-03 23:21 UTC, NanaJimsheleishvili commented on EcoTrackerApp/EcoTrackerApp/WeatherPage/WeatherPageModel.swift
> +struct MainClass: Codable {
Decodable

2023-12-03 23:21 UTC, NanaJimsheleishvili commented on EcoTrackerApp/EcoTrackerApp/WeatherPage/WeatherPageModel.swift
> +struct Weather: Codable {
Decodable

2023-12-03 23:21 UTC, NanaJimsheleishvili commented on EcoTrackerApp/EcoTrackerApp/WeatherPage/WeatherPageVC.swift
> +final class WeatherPageVC: UIViewController {
WeatherPageViewController
არშეამოკლო

2023-12-03 23:21 UTC, NanaJimsheleishvili commented on EcoTrackerApp/EcoTrackerApp/WeatherPage/WeatherPageVC.swift
> +        view.backgroundColor = UIColor.systemCyan
ეს და ქვედა ხაზი ცალცაკე მეთოდებში გაიტანე

2023-12-03 23:21 UTC, NanaJimsheleishvili commented on EcoTrackerApp/EcoTrackerApp/WeatherPage/WeatherPageVC.swift
> +        setupLatitudeTextField()
ამდენ ქონსთრეინთებს ერთი სტეკ ვიუ არაწყენდა

2023-12-03 23:21 UTC, NanaJimsheleishvili commented on EcoTrackerApp/EcoTrackerApp/WeatherPage/WeatherPageVC.swift
> +        showWeatherButton.addTarget(self, action: #selector(showWeatherButtonTapped), for: .touchUpInside)
addAction

2023-12-03 23:21 UTC, NanaJimsheleishvili commented on EcoTrackerApp/EcoTrackerApp/WeatherPage/WeatherPageViewModel.swift
> +import NetworkService
ამის მერე ერთი ენტერი

2023-12-03 23:21 UTC, NanaJimsheleishvili commented on EcoTrackerApp/EcoTrackerApp/WeatherPage/WeatherPageViewModel.swift
> +    var weatherModel: WeatherPageModel?
ამას არიყენებ და წაშალე

2023-12-03 23:21 UTC, NanaJimsheleishvili commented on EcoTrackerApp/EcoTrackerApp/WeatherPage/WeatherPageViewModel.swift
> +
ბევრი ენტერია