Species branch
Tparuna1/TBCAcademyTeamWork pull request #5
Opened 2023-12-01 12:38 UTC by slapiashvili

add species branch

2023-12-01 12:58 UTC, levanl commented on EcoTrackerApp/EcoTrackerApp/SpeciesPage/SpeciesPageVC.swift
> +final class SpeciesPageVC: UIViewController, UITableViewDataSource, UITableViewDelegate, UISearchBarDelegate {
უმჯებესია UITableViewDataSource, UITableViewDelegate, UISearchBarDelegate - ესენი extension ში გაიტანო და იქ გაწერო.

2023-12-01 13:00 UTC, Tparuna1 commented on EcoTrackerApp/EcoTrackerApp/SpeciesPage/SpeciesPageVC.swift
> +    }
UiSetup Private

2023-12-01 13:00 UTC, Tparuna1 commented on EcoTrackerApp/EcoTrackerApp/SpeciesPage/SpeciesPageViewModel.swift
> +
ფექიჯია გამოსაყენებელი პირადი ნეთვორქინგი არა.

2023-12-01 14:13 UTC, ketto26 requested changes

2023-12-01 14:13 UTC, ketto26 commented on EcoTrackerApp/EcoTrackerApp/SpeciesPage/SpeciesPageViewModel.swift
> +
import NetworkService და შენი ნეთვორქსერვისი აღარ მოგიწევს

2023-12-01 15:33 UTC, levanl approved these changes

2023-12-01 15:55 UTC, slapiashvili commented on EcoTrackerApp/EcoTrackerApp/SpeciesPage/SpeciesPageVC.swift
> +final class SpeciesPageVC: UIViewController, UITableViewDataSource, UITableViewDelegate, UISearchBarDelegate {
ეს ყველა გადავიტანე ექსთენებში. მადლობა ლევან

2023-12-01 15:55 UTC, slapiashvili commented on EcoTrackerApp/EcoTrackerApp/SpeciesPage/SpeciesPageVC.swift
> +    }
ესენი ექსთენშენებშია და ინთერნალად უნდა იყოს და დავტოვე

2023-12-01 15:56 UTC, slapiashvili commented on EcoTrackerApp/EcoTrackerApp/SpeciesPage/SpeciesPageViewModel.swift
> +
დავაედითე და საერთო networkService-ს ვიყენებ ახლა.
მადლობა ქეთო

2023-12-01 15:56 UTC, slapiashvili commented on EcoTrackerApp/EcoTrackerApp/SpeciesPage/SpeciesPageViewModel.swift
> +
დავაედითე და საერთო networkService-ს ვიყენებ ახლა.
მადლობა ქეთო

2023-12-01 16:01 UTC, Tparuna1 approved these changes
კარგია გამპსწორებული

2023-12-01 16:02 UTC, ketto26 approved these changes
APPROVED! GOOD!

2023-12-01 16:36 UTC, ketto26 approved these changes

2023-12-01 18:26 UTC, MariamKipiani approved these changes
✅

2023-12-01 18:27 UTC, merged

2023-12-03 23:06 UTC, NanaJimsheleishvili commented on EcoTrackerApp/EcoTrackerApp/SpeciesPage/SpeciesPageVC.swift
> +final class SpeciesPageVC: UIViewController {
SpeciesPageViewController
არშეამოკლო

2023-12-03 23:06 UTC, NanaJimsheleishvili commented on EcoTrackerApp/EcoTrackerApp/SpeciesPage/SpeciesPageVC.swift
> +    private var viewModel: SpeciesPageViewModel!
let 
! ამას მოერიდე
? ი რომ იყოს უკეთესია

2023-12-03 23:06 UTC, NanaJimsheleishvili commented on EcoTrackerApp/EcoTrackerApp/SpeciesPage/SpeciesPageVC.swift
> +    override func viewDidAppear(_ animated: Bool) {
ეს არუნდაგჭირდებოდეს წესით

2023-12-03 23:06 UTC, NanaJimsheleishvili commented on EcoTrackerApp/EcoTrackerApp/SpeciesPage/SpeciesPageVC.swift
> +            print("City name is empty")
წაშალე

2023-12-03 23:06 UTC, NanaJimsheleishvili commented on EcoTrackerApp/EcoTrackerApp/SpeciesPage/SpeciesPageVC.swift
> +        print("Fetching data for city: \(cityName)")
ესეც

2023-12-03 23:06 UTC, NanaJimsheleishvili commented on EcoTrackerApp/EcoTrackerApp/SpeciesPage/SpeciesPageVC.swift
> +                    print("Reload Data Called")
ესეც

2023-12-03 23:06 UTC, NanaJimsheleishvili commented on EcoTrackerApp/EcoTrackerApp/SpeciesPage/SpeciesPageVC.swift
> +        viewModel.fetchData(for: cityName) { [weak self] result in
კონტროლერში სერვის ქოლის რესფონსის success and failure არუნდაიჰენდლებოდეს. ეს მოდელის საქმეა

2023-12-03 23:06 UTC, NanaJimsheleishvili commented on EcoTrackerApp/EcoTrackerApp/SpeciesPage/SpeciesPageVC.swift
> +final class SpeciesPageTableViewCell: UITableViewCell {
ცალკე ფაილში უნდა იყოს

არგამოიწვევდა ეგ კომფლიქტს დამერჯვისას

2023-12-03 23:06 UTC, NanaJimsheleishvili commented on EcoTrackerApp/EcoTrackerApp/SpeciesPage/SpeciesPageVC.swift
> +    private let nameLabel: UILabel = {
private let nameLabel = UILabel() ესე საკმარისი იქნებოდა აქაც და ყველგან დანარჩენგან

2023-12-03 23:06 UTC, NanaJimsheleishvili commented on EcoTrackerApp/EcoTrackerApp/SpeciesPage/SpeciesPageVC.swift
> +        if let species = species {
ძაან ჩადგმული კოდია, და რამენაირაად დაშლა უკეთესი იქნებოდა ასევე
`        if let species`  საკმარისია

2023-12-03 23:06 UTC, NanaJimsheleishvili commented on EcoTrackerApp/EcoTrackerApp/SpeciesPage/SpeciesPageViewModel.swift
> +final class SpeciesPageViewModel {
ამას უნდა ჰქონდეს დელეგატი და ეს უნდა ისროდეს საქსესისას ერთ მეთოდს და ფეილზე მეორეს

2023-12-03 23:06 UTC, NanaJimsheleishvili commented on EcoTrackerApp/EcoTrackerApp/SpeciesPage/SpeciesPageViewModel.swift
> +    func fetchData(for cityName: String, completion: @escaping (Result<Void, APIError>) -> Void) {
ვაიჰ :/ უზარმაზარია

2023-12-03 23:06 UTC, NanaJimsheleishvili commented on EcoTrackerApp/EcoTrackerApp/SpeciesPage/SpeciesPageViewModel.swift
> +                    NetworkService.fetchData(from: speciesDataURL, completion: { (result: Result<SpeciesCountResponse, Error>) in
ეს ცალკე მეთოდში  და weak self